In [ ]:
!pwd

/content


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
tata = pd.read_csv('train5.csv', decimal=',')

In [ ]:
lala = pd.read_csv('Latihan01.csv', decimal=',')

In [ ]:
tata

h_0;h_1;h_2;h_3;h_4;status
0 34404;0  68715;0  69912;0  2066;0                     78758;0
  05118;0  02168;-0 35874;0  67828;0                    28521;2
  55498;0  33792;-0 92178;0  91241;0                     7848;2
  01134;0  92072;-0 67982;0  03124;0                    58931;2
  84702;0  60159;-0 66398;0  70997;0                    38701;2
...                                                         ...
  80158;0  04474;0  24985;0  39159;0                    85916;0
  00569;0  67953;0  77433;0  96257;0                    30321;0
  99412;-0 53149;-0 11107;-0 39314;0                    79514;3
  45205;0  02001;-0 6733;0   85855;0                    14457;2
  37498;0  9651;-0  97453;0  45129;0                    33865;2

[1045 rows x 1 columns]

In [ ]:
lala


x1        x2         y
0   -0.365057 -0.319084  0.273112
1    1.915594  0.129009  1.657577
2   -1.416086 -0.431537 -0.553012
3   -1.453220 -1.454493  1.455766
4    1.301988 -0.301599  1.905186
..        ...       ...       ...
145  0.454394  1.117911 -1.781428
146 -0.934667 -0.190650 -0.553367
147  1.929511  0.927888  0.073735
148 -0.872532 -1.033666  1.194801
149  0.881319  0.226273  0.428773

[150 rows x 3 columns]

In [ ]:
tata.head()

h_0;h_1;h_2;h_3;h_4;status
0 34404;0 68715;0  69912;0 2066;0                     78758;0
  05118;0 02168;-0 35874;0 67828;0                    28521;2
  55498;0 33792;-0 92178;0 91241;0                     7848;2
  01134;0 92072;-0 67982;0 03124;0                    58931;2
  84702;0 60159;-0 66398;0 70997;0                    38701;2

In [ ]:
batas = lala.values.shape[0] * 8//10
x_train = lala.values[ : batas, : -1]
y_train = lala.values[ : batas, -1]
x_test = lala.values[batas: , : -1]
y_test = lala.values[batas: , -1]


In [ ]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(120, 2)
(120,)
(30, 2)
(30,)


In [ ]:
print(x_train)
print(y_train)

[[-0.36505662 -0.31908426]
 [ 1.9155943   0.12900877]
 [-1.41608572 -0.43153678]
 [-1.45322024 -1.45449333]
 [ 1.30198777 -0.3015992 ]
 [-0.08313747 -1.50049908]
 [-0.88694404  1.91205143]
 [ 0.26009796 -0.11946306]
 [ 0.13833812 -0.39696617]
 [ 1.00414687 -0.63592421]
 [-1.15434179 -1.28486888]
 [-0.22624757  1.53564625]
 [ 1.71623288 -0.89942644]
 [ 1.43521119  1.39417657]
 [-0.49828524 -0.73384722]
 [-0.95309256  0.30129821]
 [ 1.01513807 -1.49085155]
 [-0.466351    0.6554036 ]
 [-0.27104356 -1.60065222]
 [-0.86251622 -1.22145347]
 [ 0.56733187  1.3607563 ]
 [ 1.42211536 -0.64457672]
 [-0.08349435 -0.57728527]
 [ 0.3415129   0.21369939]
 [-0.4127574  -1.46666808]
 [-1.54215134  1.55338359]
 [ 1.61026504  1.45920351]
 [-0.04596876  0.50182677]
 [ 0.50507174 -0.65241458]
 [-0.91113437  1.98476537]
 [-1.97716183 -0.5736858 ]
 [ 0.95778926  1.56968193]
 [-1.87398331 -1.19890217]
 [ 1.93124509  0.67513243]
 [-1.25593873 -0.56988569]
 [ 1.3405805   0.18063742]
 [ 0.06218616  0.47543915]
 

In [ ]:
#Algoritma Hubber

In [ ]:
from sklearn.linear_model import HuberRegressor
huber = HuberRegressor()
huber.fit(x_train, y_train)
y_pred = huber.predict(x_test)
y_pred

array([-4.99471814, -2.9487546 , -0.8418904 , -3.91463568, -3.59722225,
        4.64811894,  1.91481331,  1.86465564, -4.36350585,  2.19972186,
       -0.48209872, -1.06578493, -2.10033136, -0.61301735,  3.12068224,
       -2.24404237, -1.22685565,  1.30638706,  1.0938627 , -1.27142699,
        0.22359678, -4.00887911,  1.12248833,  0.78368611,  1.62325382,
       -1.7814281 , -0.55336706,  0.07373504,  1.19480067,  0.42877312])

In [ ]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_pred, y_test)
print(mae)

3.585021182694881e-10


In [ ]:
#Algorima Lasso

In [ ]:
from sklearn.linear_model import Lasso
Lasso = Lasso()
Lasso.fit(x_train, y_train)
y_pred = Lasso.predict(x_test)
y_pred

array([-1.86072511, -1.20919219, -1.0066799 , -1.95871411, -1.41917809,
        1.73136993,  1.92133606,  1.25538788, -1.38982631,  0.86683139,
       -0.84922894, -1.71674439, -0.72836047, -0.11344116,  1.77247493,
       -2.17359735,  0.27247484,  1.29624817,  0.8465963 , -1.77883489,
        0.10286784, -1.38794065,  1.38999032,  0.07611248,  0.28370578,
       -1.28329374,  0.17715916, -1.06514769,  1.12149073, -0.28318996])

In [ ]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_pred,y_test)
print("Mae = ", mae)

Mae =  1.059765346685561


In [ ]:
#algoritma Ridge

In [ ]:
from sklearn.linear_model import Ridge
Ridge = Ridge()
Ridge.fit(x_train, y_train)
y_pred = Ridge.predict(x_test)
y_pred

array([-4.9571673 , -2.92729228, -0.83921133, -3.88766872, -3.57067715,
        4.61230924,  1.90551323,  1.85267525, -4.32964186,  2.18276383,
       -0.48204606, -1.06436696, -2.08454414, -0.60825732,  3.09937901,
       -2.23374532, -1.21451839,  1.29983092,  1.08717081, -1.26837588,
        0.22154102, -3.97832903,  1.11809876,  0.77625577,  1.60893878,
       -1.77125413, -0.54779126,  0.06755815,  1.18846339,  0.42296861])

In [ ]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_pred,y_test)
print(mae)

0.01327267673346396


In [ ]:
#classification

In [ ]:
tata = pd.read_csv('train5.csv', delimiter=';', decimal=',')
tata

h_0      h_1      h_2      h_3      h_4  status
0     0.34404  0.68715  0.69912  0.20660  0.78758       0
1    -0.05118  0.02168 -0.35874  0.67828  0.28521       2
2    -0.55498  0.33792 -0.92178  0.91241  0.78480       2
3    -0.01134  0.92072 -0.67982  0.03124  0.58931       2
4    -0.84702  0.60159 -0.66398  0.70997  0.38701       2
...       ...      ...      ...      ...      ...     ...
1040  0.80158  0.04474  0.24985  0.39159  0.85916       0
1041  0.00569  0.67953  0.77433  0.96257  0.30321       0
1042 -0.99412 -0.53149 -0.11107 -0.39314  0.79514       3
1043 -0.45205  0.02001 -0.67330  0.85855  0.14457       2
1044 -0.37498  0.96510 -0.97453  0.45129  0.33865       2

[1045 rows x 6 columns]

In [ ]:
batas = tata.values.shape[0] * 8//10
x_train = tata.values[ : batas, : -1]
y_train = tata.values[ : batas, -1]
x_test = tata.values[batas: , : -1]
y_test = tata.values[batas: , -1]

In [ ]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(836, 5)
(836,)
(209, 5)
(209,)


In [ ]:
y_train

array([0., 2., 2., 2., 2., 2., 2., 0., 1., 2., 1., 0., 2., 0., 1., 3., 0.,
       1., 3., 3., 3., 2., 3., 1., 2., 0., 0., 2., 0., 0., 0., 2., 3., 3.,
       3., 0., 0., 3., 3., 3., 0., 0., 3., 1., 2., 3., 0., 0., 1., 2., 0.,
       3., 0., 1., 2., 3., 3., 1., 2., 1., 3., 3., 0., 0., 1., 2., 0., 1.,
       2., 3., 3., 0., 2., 1., 1., 3., 3., 3., 2., 2., 0., 0., 2., 0., 0.,
       2., 2., 3., 1., 1., 3., 3., 2., 3., 1., 2., 0., 3., 3., 0., 3., 1.,
       0., 3., 0., 3., 0., 1., 1., 0., 3., 2., 0., 1., 0., 0., 0., 0., 0.,
       1., 3., 0., 3., 3., 2., 1., 0., 2., 2., 0., 2., 0., 2., 1., 2., 1.,
       1., 3., 1., 2., 2., 3., 3., 1., 2., 1., 3., 2., 1., 1., 2., 2., 2.,
       2., 3., 0., 1., 0., 3., 3., 2., 2., 2., 3., 3., 1., 0., 1., 1., 0.,
       2., 0., 1., 2., 3., 3., 0., 2., 0., 0., 0., 3., 3., 1., 2., 2., 2.,
       1., 2., 3., 0., 1., 3., 2., 0., 2., 0., 2., 1., 1., 2., 0., 0., 0.,
       3., 3., 1., 0., 1., 2., 1., 3., 1., 1., 1., 3., 2., 2., 1., 1., 0.,
       2., 0., 1., 0., 2.

In [ ]:
from sklearn.naive_bayes import GaussianNB
otak = GaussianNB()
otak.fit(x_train, y_train)


GaussianNB()

In [ ]:
y_pred = otak.predict(x_test)
y_pred

array([2., 1., 3., 1., 3., 3., 0., 2., 0., 1., 1., 3., 0., 2., 1., 1., 3.,
       3., 0., 2., 3., 1., 3., 1., 1., 0., 3., 2., 3., 3., 2., 2., 0., 2.,
       0., 3., 2., 0., 0., 3., 2., 1., 1., 2., 1., 1., 1., 2., 0., 0., 2.,
       2., 3., 2., 3., 1., 1., 2., 2., 0., 2., 1., 1., 3., 0., 2., 3., 0.,
       0., 2., 2., 0., 3., 2., 1., 2., 2., 1., 3., 2., 0., 1., 3., 1., 2.,
       1., 1., 0., 3., 0., 1., 0., 2., 3., 2., 1., 0., 1., 2., 1., 0., 2.,
       3., 1., 1., 3., 2., 2., 1., 2., 1., 3., 2., 2., 1., 3., 2., 1., 0.,
       3., 0., 2., 2., 1., 1., 3., 1., 0., 2., 1., 1., 2., 0., 3., 0., 1.,
       3., 1., 1., 1., 1., 1., 0., 2., 1., 0., 0., 1., 3., 0., 0., 3., 3.,
       0., 3., 0., 3., 1., 2., 0., 3., 3., 2., 3., 1., 0., 1., 0., 3., 3.,
       1., 3., 0., 1., 2., 1., 2., 1., 2., 1., 3., 3., 0., 2., 3., 0., 3.,
       2., 0., 0., 3., 1., 0., 1., 0., 1., 2., 0., 0., 0., 1., 0., 3., 2.,
       0., 0., 3., 2., 2.])

In [ ]:
y_test

array([2., 1., 3., 1., 3., 3., 0., 2., 0., 1., 1., 3., 0., 2., 1., 1., 3.,
       3., 0., 2., 3., 1., 3., 1., 1., 0., 3., 2., 3., 3., 2., 2., 0., 2.,
       0., 3., 2., 0., 0., 3., 2., 1., 1., 2., 1., 1., 1., 2., 0., 0., 2.,
       2., 3., 2., 3., 1., 1., 2., 2., 0., 2., 1., 1., 3., 0., 2., 3., 0.,
       0., 2., 2., 0., 3., 2., 1., 2., 2., 1., 3., 2., 0., 1., 3., 1., 2.,
       1., 1., 0., 3., 0., 1., 0., 2., 3., 2., 1., 0., 1., 2., 1., 0., 2.,
       3., 1., 1., 3., 2., 2., 1., 2., 1., 3., 2., 2., 1., 3., 2., 1., 0.,
       3., 0., 2., 2., 1., 1., 3., 1., 0., 2., 1., 1., 2., 0., 3., 0., 1.,
       3., 1., 1., 1., 1., 1., 0., 2., 1., 0., 0., 1., 3., 0., 0., 3., 3.,
       0., 3., 0., 3., 1., 2., 0., 3., 3., 2., 3., 1., 0., 1., 0., 3., 3.,
       1., 3., 0., 1., 2., 1., 2., 1., 2., 1., 3., 3., 0., 2., 3., 0., 3.,
       2., 0., 0., 3., 1., 0., 1., 0., 1., 2., 0., 0., 0., 1., 0., 3., 2.,
       0., 0., 3., 2., 2.])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

1.0

In [240]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred, y_test)

array([[50,  0,  0,  0],
       [ 0, 59,  0,  0],
       [ 0,  0, 52,  0],
       [ 0,  0,  0, 48]])

In [242]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        50
         1.0       1.00      1.00      1.00        59
         2.0       1.00      1.00      1.00        52
         3.0       1.00      1.00      1.00        48

    accuracy                           1.00       209
   macro avg       1.00      1.00      1.00       209
weighted avg       1.00      1.00      1.00       209

